version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: silvin-lanka-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://root:password@db:3306/tourlk
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=changeme
    depends_on:
      - db
    networks:
      - silvin-lanka-net
    volumes:
      - ./public/uploads:/app/public/uploads

  db:
    image: mysql:8.0
    container_name: silvin-lanka-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: silvin_lanka
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - silvin-lanka-net

volumes:
  db_data:


networks:
  silvin-lanka-net:
    driver: bridge
